LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

SingleSpaceBeforeFirstArg:
  Enabled: false

TrailingComma:
  Enabled: false

Style/LeadingCommentSpace:
  Exclude:
    - 'Berksfile'

Style/FileName:
  Exclude:
    - 'Berksfile'

