name             'rails'
maintainer       'Alexander Merkulov'
maintainer_email 'sasha@merqlove.ru'
license          'Apache 2.0'
description      'Installs/Configures ruby/rails, php, databases and so on'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '1.0.0'

supports 'centos'
supports 'ubuntu'

depends 'openssl'
depends 'openssl-fips'
depends 'swap'
depends 'iptables'
depends 'ssh_known_hosts'
depends 'nginx'
depends 'rbenv'
depends 'mongodb'
depends 'postgresql'
depends 'mysql'
depends 'yum'
depends 'yum-epel'
depends 'apt'
depends 'database'
depends 'php'
depends 'php-fpm'
depends 'composer'
depends 'msmtp'
depends 'selinux'
depends 'nodejs'
depends 'python'
depends 'nodejs'
depends 'newrelic'
depends 'openssh'
depends 'vsftpd'
depends 'duplicity_ng'
